// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: bupcket/bupcket.proto

package bupcket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type UploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bupcket_bupcket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bupcket_bupcket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_bupcket_bupcket_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

// The response message containing the greetings
type UploadReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *UploadReply) Reset() {
	*x = UploadReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bupcket_bupcket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReply) ProtoMessage() {}

func (x *UploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_bupcket_bupcket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReply.ProtoReflect.Descriptor instead.
func (*UploadReply) Descriptor() ([]byte, []int) {
	return file_bupcket_bupcket_proto_rawDescGZIP(), []int{1}
}

func (x *UploadReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_bupcket_bupcket_proto protoreflect.FileDescriptor

var file_bupcket_bupcket_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x75, 0x70, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x62, 0x75, 0x70, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x75, 0x70, 0x63, 0x6b, 0x65, 0x74,
	0x22, 0x23, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x1f, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x32, 0x40, 0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x36, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x16, 0x2e, 0x62, 0x75, 0x70, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x62, 0x75, 0x70, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6e, 0x69, 0x63, 0x6f, 0x64, 0x2f, 0x62, 0x75,
	0x70, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bupcket_bupcket_proto_rawDescOnce sync.Once
	file_bupcket_bupcket_proto_rawDescData = file_bupcket_bupcket_proto_rawDesc
)

func file_bupcket_bupcket_proto_rawDescGZIP() []byte {
	file_bupcket_bupcket_proto_rawDescOnce.Do(func() {
		file_bupcket_bupcket_proto_rawDescData = protoimpl.X.CompressGZIP(file_bupcket_bupcket_proto_rawDescData)
	})
	return file_bupcket_bupcket_proto_rawDescData
}

var file_bupcket_bupcket_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bupcket_bupcket_proto_goTypes = []interface{}{
	(*UploadRequest)(nil), // 0: bupcket.UploadRequest
	(*UploadReply)(nil),   // 1: bupcket.UploadReply
}
var file_bupcket_bupcket_proto_depIdxs = []int32{
	0, // 0: bupcket.Upload.Send:input_type -> bupcket.UploadRequest
	1, // 1: bupcket.Upload.Send:output_type -> bupcket.UploadReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bupcket_bupcket_proto_init() }
func file_bupcket_bupcket_proto_init() {
	if File_bupcket_bupcket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bupcket_bupcket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bupcket_bupcket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bupcket_bupcket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bupcket_bupcket_proto_goTypes,
		DependencyIndexes: file_bupcket_bupcket_proto_depIdxs,
		MessageInfos:      file_bupcket_bupcket_proto_msgTypes,
	}.Build()
	File_bupcket_bupcket_proto = out.File
	file_bupcket_bupcket_proto_rawDesc = nil
	file_bupcket_bupcket_proto_goTypes = nil
	file_bupcket_bupcket_proto_depIdxs = nil
}
